#!/bin/bash

GOBIN='go'

cleanArtifacts() {
    echo "cleaning artifacts"
    [ -d ./bin ] && rm -rf ./bin
    mkdir -p ./bin
    if [ -d ./bin ] && [ -f .env-example ]; then cp .env-example ./bin/.env; fi
}

buildTaxi() {
    # local oses=(windows darwin)
    # local arch="arm64"
    # env GOOS=${os} GOARCH=${arch}
    #
    ${GOBIN} build -work -ldflags="-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn" -o bin/taxi
}
####
cleanArtifacts
buildTaxi
####
